### ISSUE TITLE
get_fwhm crashing [polyfit]

### ISSUE THREAD

**Issue by SergioLordano** [oasys-lnls-kit/optlnls#4]
`get_fwhm()` crashes when vector is empty in `np.polyfit`. A workaround must be implemented with `try` and `except`.

```
Traceback (most recent call last):

  File "/home/ABTLUS/sergio.lordano/py38/lib/python3.8/site-packages/spyder_kernels/py3compat.py", line 356, in compat_exec
    exec(code, globals, locals)

  File "/home/ABTLUS/sergio.lordano/data/cedro/commissioning/2023-07-24/caustics_cedro.py", line 130, in <module>
    plot_beam(mtx, cut=0, textB=5, textC=10, cmap=cmap, show_colorbar=1,

  File "/home/ABTLUS/sergio.lordano/py38/lib/python3.8/site-packages/optlnls/plot.py", line 325, in plot_beam
    z_cut_fit_fwhm = get_fwhm(z_axis, z_cut_fit, oversampling=overSampling, zero_padding=fwhm_zeroPadding, avg_correction=True, threshold=fwhm_threshold, inmost_outmost=fwhm_int_ext)

  File "/home/ABTLUS/sergio.lordano/py38/lib/python3.8/site-packages/optlnls/math.py", line 242, in get_fwhm
    popt_left = np.polyfit(left_fine_x[left_hwhm_idx-1 : left_hwhm_idx+2], left_fine_y[left_hwhm_idx-1 : left_hwhm_idx+2] , 1)

  File "<__array_function__ internals>", line 180, in polyfit

  File "/home/ABTLUS/sergio.lordano/py38/lib/python3.8/site-packages/numpy/lib/polynomial.py", line 638, in polyfit
    raise TypeError("expected non-empty vector for x")

TypeError: expected non-empty vector for x
```

**Comment by SergioLordano** [comment]
Fixed. Used try/except. Also noted that `plot_beam` was using `avg_correction=True` for the fitted curves. Changed to `False`.
